// Banco de Dados do Playbook - Versão Integral Sem Cortes
const dbHistorias = [
    {
        titulo: "História 1: Bruno & Cristiane (Bateria & Potência)",
        dialogos: [
            { type: "narrativa", text: "SIMULAÇÃO 1 - Promotor e Cliente\nJornada completa com UX" },
            { type: "etapa", text: "Chegada e abordagem" },
            { type: "narrativa", text: "A cliente entra na loja olhando as caixas Boombox da Concorrente 1, 2 e da Aiwa.\nEla tem um amigo que tem a Boombox da Concorrente 1 e ficou interessada.\nRecentemente ela viu a Boombox da Aiwa ao passar na frente de um quiosque na praia e foi pesquisar, então ficou muito mais interessada e esta procurando para conhecer melhor e ver se já levar pra casa.\n1ª abordagem do Promotor Aiwa.\nApós a cliente ter entrado na loja ela olhou as 3 marcas e ficou olhando, neste momento o Promotor chegou perto dela e inicia uma conversa." },
            { type: "msg", name: "PROMOTOR (Bruno)", side: "left", text: "Opa, pode aumentar aí sem medo. Eu sou o Bruno, Promotor da AIWA. Está procurando um som?" },
            { type: "msg", name: "Cristiane", side: "right", text: "Olá, estou sim, Tô dando uma olhada pois quero levar para um churrasco." },
            { type: "msg", name: "Cristiane", side: "right", text: "Vi a 'C.1' ali, mas tá salgada, mais ouvi falar muito bem da Aiwa e estava passando aqui e quando vi ela eu pensei em conhecer melhor." },
            { type: "etapa", text: "Identificando necessidade - UX" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Que legal eu vou te ajudar. Qual seu nome?" },
            { type: "msg", name: "Cristiane", side: "right", text: "Meu nome é Cristiane." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Prazer Cristiane, Então falando em churrasco, podemos unir autonomia, qualidade e Potência para durar o até o final do churrasco." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Oque você acha disso?" },
            { type: "msg", name: "Cristiane", side: "right", text: "Isso mesmo que eu quero." },
            { type: "msg", name: "Cristiane", side: "right", text: "O Churrasco deve começar umas 15h e vai até depois da janta." },
            { type: "etapa", text: "Conexão emocional - Nostalgia" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Pronto, Você já conhecia a AIWA das antigas, aquele som 3 em 1, que tinha CDs, Toca fitas e toca discos?" },
            { type: "msg", name: "Cristiane", side: "right", text: "Sim, Meu pai tem um 3 em 1 até hoje." },
            { type: "msg", name: "Cristiane", side: "right", text: "É bom demais, e ainda esta funcionando, tem um som muito bom." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "É essa mesma Aiwa!" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Lembra da Sony, ela sempre foi referência em qualidadede Áudio e Vídeo?" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Então, compramos a fabrica que foi da Sony em Manaus, e hoje a Aiwa trabalha com a melhor qualidade em seus produtos." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "e assim estamos com a nossa Boombox superando as nossas concorrentes, é isso que vou te mostrar hoje." },
            { type: "etapa", text: "Demonstração sensorial - Cereja do bolo" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Vou colocar uma musica, olha a qualidade do som e como ele é limpo e não distorce, Coloca a mão aqui do lado, sente vibrar?" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "São 200W RMS de verdade, e ela mantem a mesma Potência mesmo na bateria, já as concorrentes não conseguem segurar, entregam uma Potência quando na tomada e tirando da tomada ficando somente na bateria eles costumam ter uma perda para economizar energia." },
            { type: "msg", name: "Cristiane", side: "right", text: "Caramba, o grave é limpo." },
            { type: "msg", name: "Cristiane", side: "right", text: "Gostei do som, e sobre potência, isso é muito bom e eu não sabia." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "E a bateria segura até 30 horas em volume médio, o que da para curtir seu churrasco tranquilo." },
            { type: "msg", name: "Cristiane", side: "right", text: "Eu posso levar ela para perto da piscina e levar para praia também?" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Com certeza, temos proteção IP66." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Aguenta poeira da e jatos de água. Pode ficar tranquilo." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Imagine que algum pulou na piscina ou derrubaram algum líquido nela, você fecha o compartimento traseiro, ai poderá molhar para limpá-la, você só não pode mergulhar ela." },
            { type: "etapa", text: "Teste real com celular do cliente" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Olha ainda temos o Nosso Aplicativo Aiwa Áudio BR, Pelo app da AIWA você ainda pode dar um reforço no grave e a ainda pode escolher varios equalizadores." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Já Salva ai no celular." },
            { type: "etapa", text: "Fechamento sem pressão + handoff" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "E ai muito bem né." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Se precisar tirar alguma dúvida pode falar, tudo bem?" },
            { type: "msg", name: "Cristiane", side: "right", text: "Gostei. Quanto tá saindo?" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Essa é mais uma vantagem, ela sai bem mais batara que a C.1, com mais potência real, e ainda temos a opção de você utilizar pen-drives com músicas e ainda pode carregar seu telefone utilizando a bateria da caixa como carregador portátil." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Vou chamar o vendedor para tirar o pedido para a Senhora, tudo bem, só um minuto." },
            { type: "msg", name: "Edy", side: "left", text: "Oi, tudo bem?" },
            { type: "msg", name: "Edy", side: "left", text: "O Bruno me passou. Vamos fechar? Você leva ela hoje mesmo." },
            { type: "msg", name: "Cristiane", side: "right", text: "Vamos." },
            { type: "etapa", text: "Pós-venda - Acompanhamento até a porta" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Parabéns pela escolha!" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Qualquer dúvida do app ou se precisar de algum outro produto da Aiwa, volta aqui na loja e pode procurar pelo Bruno Promotor da Aiwa." },
            { type: "msg", name: "Cristiane", side: "right", text: "Claro eu precisando eu volto sim, muito obrigada pelo seu atendimento." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Eu quem agradeço pela sua atenção, Vou te acompanhar até a saída, tudo bem." },
            { type: "msg", name: "Cristiane", side: "right", text: "Obrigada, até logo." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Tchau até logo." }
        ]
    },
    {
        titulo: "História 2: Vendedor e Cristiane (Cliente) no Pós-Venda",
        dialogos: [
            { type: "narrativa", text: "SIMULAÇÃO 2 - Vendedor e Cristiane (Cliente) no Pós-Venda\n\n5 dias depois do churrasco - Cristiane volta na loja" },
            { type: "etapa", text: "Retorno espontâneo" },
            { type: "msg", name: "Cristiane", side: "right", text: "Ei como vai Edy, tudo bem?" },
            { type: "msg", name: "Cristiane", side: "right", text: "Vim só dar um oi." },
            { type: "msg", name: "Edy", side: "left", text: "Olá Cristiane! Que bom te ver. E aí, como foi o churrasco?" },
            { type: "msg", name: "Cristiane", side: "right", text: "Foi bom demais. ficamos até quase meia-noite e ainda tinha bateria. Meus amigos ficaram doidos." },
            { type: "etapa", text: "Escuta ativa - UX" },
            { type: "msg", name: "Edy", side: "left", text: "Que massa. e ai usou ela perto da piscina mesmo?" },
            { type: "msg", name: "Cristiane", side: "right", text: "Usei." },
            { type: "msg", name: "Cristiane", side: "right", text: "E levei pra praia no domingo. Aí fiquei com medo do sal, passei um pano úmido, fique com medo de jogar um pouco de água nela." },
            { type: "msg", name: "Edy", side: "left", text: "Sem problemas. Com IP66 você pode lavar com jato leve, só fecha bem aquela tampinha traseira." },
            { type: "msg", name: "Edy", side: "left", text: "Depois é só secar. Nada de mergulhar ela ta bem?" },
            { type: "msg", name: "Cristiane", side: "right", text: "Isso o Bruno tinha falado." },
            { type: "msg", name: "Cristiane", side: "right", text: "Outra coisa, coloquei meu celular carregar na USB, só não testei com Pendrive, uma amigo falou também algo sobre utilizar duas caixas da mesma, porém não entendi, você pode me ajudar?" },
            { type: "etapa", text: "Demonstração prática" },
            { type: "msg", name: "Edy", side: "left", text: "Ajudo sim, O Bruno me falou dessa função, é o TWS, ela permite ligar duas Boombox e somar a potênciadas duas." },
            { type: "msg", name: "Edy", side: "left", text: "Vi que você trouxe a sua Boombox, vamos testar aqui, você vai ver que legal?" },
            { type: "narrativa", text: "[pega a caixa que ela trouxe na sacola e parea as duas caixas do mesmo modelo]" },
            { type: "msg", name: "Edy", side: "left", text: "Vou por uma musica que eu vi o Bruno da Aiwa testando a caixa outro dia e gostei muito, olha agora as duas tocando junto, ficou o dobro da potência." },
            { type: "msg", name: "Edy", side: "left", text: "assim se você tiver em um um parente ou amigo com uma Boombox da Aiwa, parea as duas pra fazer a festa bombar ainda mais." },
            { type: "msg", name: "Cristiane", side: "right", text: "Nossa, verdade tenho uma amiga que estava pensando em comprar uma também, vou falar com ela." },
            { type: "msg", name: "Edy", side: "left", text: "Opa, fala com ela que pode me procurar aqui e eu ou o Bruno mostranos tudo que a Boombox tem de melhor e as vantagens que ela vai levar pra casa, temho certeza que ela vai gostar." },
            { type: "msg", name: "Cristiane", side: "right", text: "Testei também o aplicativo da Aiwa que o Bruno me passou, testei os equalizadores já definidos e testei o grave." },
            { type: "msg", name: "Cristiane", side: "right", text: "Ficou com mais grave mesmo." },
            { type: "etapa", text: "Reforço de valor e relacionamento" },
            { type: "msg", name: "Edy", side: "left", text: "Muito legal né, tem muita qualidade mesmo." },
            { type: "msg", name: "Cristiane", side: "right", text: "Todos da festa gostaram da Boomboxda Aiwa." },
            { type: "msg", name: "Edy", side: "left", text: "Pronto." },
            { type: "msg", name: "Edy", side: "left", text: "Outra coisa, o Bruno está em rota hoje, mas se precisar de algo depois, pode me chamar no zap que eu vejo com ele depois se eu nãosouber te ajudar, tudo bem." },
            { type: "msg", name: "Cristiane", side: "right", text: "Claro chamo sim. Aliás, vou falar com minha amiga viu, ela viu a minha Boombox e vou trazer ela pra você e o Bruno mostrar pra ela também." },
            { type: "msg", name: "Cristiane", side: "right", text: "Posso trazer ela aqui sábado?" },
            { type: "msg", name: "Edy", side: "left", text: "Pode trazer. Chega e pergunta pelo Edy ou pelo Bruno." },
            { type: "msg", name: "Edy", side: "left", text: "A gente faz os mesmos testes e tudo mais, tenho certeza que ela vai comprar." },
            { type: "msg", name: "Cristiane", side: "right", text: "Fechado. Obrigada, Edy." },
            { type: "msg", name: "Edy", side: "left", text: "Eu que agradeço o retorno, fico no aguardo, qualquer coisa estamos aqui, Até logo." }
        ]
    },
    {
        titulo: "História 3: Cliente traz indicação",
        dialogos: [
            { type: "narrativa", text: "SIMULAÇÃO 3 - Cliente traz indicação\nSábado.\n- Cristiane volta com a amiga Fernanda." },
            { type: "etapa", text: "Chegada com indicação" },
            { type: "msg", name: "Cristiane", side: "right", text: "Olá Edy! Cheguei." },
            { type: "msg", name: "Cristiane", side: "right", text: "Essa é a Fernanda, minha amiga do churrasco, não falei que viria com ela aqui." },
            { type: "msg", name: "Edy", side: "left", text: "Oi Cristiane, olá Fernanda, sejam bem-vindas. O Bruno tá aqui também, vou chamar ele." },
            { type: "msg", name: "Edy", side: "left", text: "Edy: Bruno Chega ai, apresenta a Boombox para a Amiga da nossa Cliente Cristiane." },
            { type: "msg", name: "PROMOTOR (Bruno)", side: "left", text: "Fala ai Edy!" },
            { type: "msg", name: "PROMOTOR (Bruno)", side: "left", text: "Ei Cristiane, olá Fernanda tudo bem com vocês. O Edy me disse que você passou aqui outro dia e ele te ajudou sobre o TWS." },
            { type: "msg", name: "Cristiane", side: "right", text: "Sim eu estava passando aqui perto e passei pra dar um oi a aproveitei pra tirar uma dúvida que ele me ajudou muito, e eu trouxe minha amiga pra comprar uma pra ela também, pode mostrar a Aiwa pra ela também?" },
            { type: "msg", name: "Cristiane", side: "right", text: "Esta aqui é minha amiga Fernanda, este é o Bruno Promotor da Aiwa." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Com certeza, vou mostrar agora." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Olá Fernanda Tudo Bem? Você esta pensando em uma caixa para utilizar, em casa, pra alguma festa ou pra utilizar em praia?" },
            { type: "msg", name: "Fernanda", side: "right", text: "No meu caso eu não quero pra festa, quero pra academia e pra levar para praia pra relaxar." },
            { type: "etapa", text: "Identificando necessidade - UX" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Perfeito, depois de uma semana de correria de trabalho, nada melhor que relaxar um pouco." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Na academia você curte uma música com mais grave ou um som mais limpo, algo ambiente?" },
            { type: "msg", name: "FERNANDA", side: "right", text: "Mais limpo, talvez algo mais agitado. Na praia eu quero algo que não estrague com areia." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Então a Boombox te atenderá perfeitamente. Vou te mostrar ela igual fiz com a Cristiane." },
            { type: "etapa", text: "Demonstração com prova social" },
            { type: "msg", name: "Edy", side: "left", text: "Vamos fazer o teste que a Cristiane viu." },
            { type: "narrativa", text: "[pega duas Boombox da loja, neste caso vamossupor que temos duas em exposição] Olha o TWS." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Conecta seu celular, Fernanda. Coloca aquela musica da playlist que você cotuma usar para treinar." },
            { type: "msg", name: "FERNANDA", side: "right", text: "Nossa, pareou as duas?[conecta]" },
            { type: "msg", name: "Edy", side: "left", text: "Isso. Uma fica de cada lado. Fica estéreo." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Isso mesmo, imagina uma cena de uma avião passando de um lado para o outro na tela da tv, você ira escutar o som estéreo como se estivesse realmente passando como na cena." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "e ainda ela soma a potência das duas caixas, então voce passa a ter 400W que pura qualidade." },
            { type: "msg", name: "Cristiane", side: "right", text: "Viu?" },
            { type: "msg", name: "Cristiane", side: "right", text: "Foi isso que eu te falei." },
            { type: "etapa", text: "Conexão emocional + diferencial" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "E você faou de ir na praia, ela tem proteção que permite que porssa ir napraia sem preocupação e o IP66?" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Areia da praia não entra. Fecha a tampinha, depois é só passar água doce." },
            { type: "msg", name: "FERNANDA", side: "right", text: "E a bateria?" },
            { type: "msg", name: "FERNANDA", side: "right", text: "Eu fico 2 horas na academia." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Você tem em media 30h no volume médio, vai ficar dias sem ter que recarregar." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Talvez cerregue ela uma ou duas vezs na semana, vai depender do seu uso and do volume." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "E pode utilizar a carga da Boombox para carrega seu celular quando precisar. Igual a Cristiane aprendeu aqui." },
            { type: "etapa", text: "Fechamento natural" },
            { type: "msg", name: "FERNANDA", side: "right", text: "Quanto tá? A C.1 tá quase mil a mais." },
            { type: "msg", name: "Edy", side: "left", text: "Essa sai bem mais em conta, com garantia de Aiwa. Quer levar hoje?" },
            { type: "msg", name: "FERNANDA", side: "right", text: "Quero." },
            { type: "msg", name: "FERNANDA", side: "right", text: "Vou levar igual a dela." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Execelente escolha. Cristiane, valeu pela indicação." },
            { type: "msg", name: "Cristiane", side: "right", text: "Imagina." },
            { type: "msg", name: "Cristiane", side: "right", text: "Agora a gente faz o treino juntas." },
            { type: "msg", name: "Edy", side: "left", text: "Vou lá no caixa fechar pra você, Fernanda." },
            { type: "msg", name: "Edy", side: "left", text: "Bruno pode pegar a Boombox pra ela enquanto tiro pedido dela?" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Claro, aqui esta a caixa dela, Qualquer dúvida pode passar aqui que eu ou o vendedor podemos te ajudar." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Bem-vinda a família Aiwa.\nVou acompanhar voces duas até a porta ok, parabéns pela compra, volte sempre." }
        ]
    },
    {
        titulo: "História 4: Treinamento prático e relacionamento",
        dialogos: [
            { type: "narrativa", text: "SIMULAÇÃO 4 – Treinamento prático e relacionamento\n- Bruno treinando o Edy na loja, fim do dia" },
            { type: "etapa", text: "Treinamento TWS – ouvir médio, grave e agudo" },
            { type: "msg", name: "PROMOTOR (Bruno)", side: "left", text: "Edy, vem aqui." },
            { type: "msg", name: "PROMOTOR (Bruno)", side: "left", text: "Vamos parear duas Boombox rapidinho. Faremos igual você fez quando a cliente Cristiane retornou na loja e indicou para a amiga dela que veio e comprou uma igual." },
            { type: "msg", name: "VENDEDOR (Edy)", side: "left", text: "Pareado." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Agora coloca essa música aqui, tem grave marcado, médio e agudo." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Coloca a mão aqui do lado, sente vibrar?" },
            { type: "msg", name: "Edy", side: "left", text: "Sinto, sim." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Isso is o grave." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Agora presta atenção na clareza dos instrumentos, como você consegue ouvir vários separadamente." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "O som não fica embolado como em muitas caixas do mercado. É aqui que o cliente se liga." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Sempre que puder, faz o cliente ter esta experiência." },
            { type: "msg", name: "Edy", side: "left", text: "Deu para notar tudo. Vou fazer sempre." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Então, você pode falar com o cliente assim. Não fale somente da potência de \"200W RMS\"." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Fale: \"coloca a mão, sente o grave\". O cliente entende na hora." },
            { type: "etapa", text: "Aplicativo Aiwa Áudio BR" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Abre o app Aiwa Áudio BR. Conecta na caixa." },
            { type: "msg", name: "Edy", side: "left", text: "Conectei." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Aqui tem o Bass Boost. Liga. Sentiu a diferença?" },
            { type: "msg", name: "Edy", side: "left", text: "O grave aumentou." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Desliga. Agora vai em equalizadores." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Tem Rock, Pop, Sertanejo, etc. Mostra pro cliente e fala: \"escolhe o que fica melhor pra sua música\"." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Deixa ele testar, assim ele vai ter a experiência real." },
            { type: "msg", name: "Edy", side: "left", text: "E o TWS, tem algum exemplo que posso mostrar?" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Sim. Depois de parear, mostra as duas tocando e fala do estéreo." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Diz: \"imagina um carro de corrida ou avião passando de um lado pro outro\". O cliente lembra disso." },
            { type: "etapa", text: "Como replicar com o cliente" },
            { type: "msg", name: "PROMOTOR", side: "left", text: "Resumo: 1. Pergunta o uso. 2. Pareia." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "3. Manda sentir o grave com a mão. 4. Mostra médio e agudo." },
            { type: "msg", name: "PROMOTOR", side: "left", text: "5. Abre o app, liga o Bass Boost, troca equalizador. 6. Deixa ele escolher." },
            { type: "msg", name: "VENDEDOR", side: "left", text: "Anotado." },
            { type: "msg", name: "Edy", side: "left", text: "Então, bora." },
            { type: "msg", name: "Edy", side: "left", text: "Amanhã vamos montar uma ilha juntos e eu vou trazer o material novo." }
        ]
    }
];
